global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - /etc/prometheus/rules.yml
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets:
        - local-pushgateway:9091
